name: BRVM Stock Data Scraper

on:
  push:                             # Trigger on push
  schedule:
    - cron: '0 15 * * 1-5'          # 10:00 UTC Monday to Friday
  workflow_dispatch:               # Manual trigger from GitHub

jobs:
  scrape_and_store:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Debug file presence
      run: |
        pwd
        ls -R

    - name: Run scraper
      env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
      run: |
        python actions.py
